alias g.='git'
alias g.s='git status'
alias g.ch='git checkout'
alias g.chm='git checkout master'
alias g.c='git commit -m'
alias g.ca='git commit --amend'
alias g.cf='git commit --fixup'
alias g.a='git add'
alias g.ap='git add -p'
alias g.an='git add -N'
alias g.an.='git add -N .'
alias g.r='git reset'
alias g.rb='git rebase'
alias g.rbi='git rebase -i'
alias g.rbim='git rebase -i master'
alias g.rbc='git rebase --continue'
alias g.rba='git rebase --abort'
alias g.l='git lol'
alias g.p='git pushf'
alias g.pull='git pull'
alias g.br='git branch'

alias c.='cargo'
alias c.b='cargo build'
alias c.t='cargo test'
alias c.bench='rustup run nightly cargo bench'
alias c.r='cargo run'

alias v='vim'
alias e='vim ~/.bash_aliases'

alias s.pg='sudo -u postgres psql postgres'

alias p='cd ~/Projects'
alias p.pd='cd ~/Projects/Tom/MassFillPadDesign'

alias python='python3'
